#!/usr/bin/env python3
"""
Environment Setup Script for Secure Agentic Browser
This script helps you set up your .env file with proper configuration
"""

import os
import shutil
from pathlib import Path

def create_env_file():
    """Create .env file from template with user input."""
    print("🔧 Secure Agentic Browser Environment Setup")
    print("=" * 60)
    
    env_file = Path(".env")
    template_file = Path(".env.template")
    
    # Check if .env already exists
    if env_file.exists():
        print("⚠️  .env file already exists!")
        response = input("Do you want to overwrite it? (y/n): ").strip().lower()
        if response not in ['y', 'yes']:
            print("❌ Setup cancelled")
            return False
    
    # Check if template exists
    if not template_file.exists():
        print("❌ .env.template not found!")
        return False
    
    print("\n📝 Let's set up your environment variables...")
    
    # Get Gemini API Key
    print("\n🔑 GOOGLE GEMINI API KEY (Required)")
    print("Get your API key from: https://makersuite.google.com/app/apikey")
    api_key = input("Enter your Gemini API key: ").strip()
    
    if not api_key or api_key == "your_actual_gemini_api_key_here":
        print("❌ Valid API key is required!")
        return False
    
    # Optional configurations
    print("\n⚙️  OPTIONAL CONFIGURATIONS")
    print("Press Enter to use defaults, or provide custom values:")
    
    # Browser settings
    headless = input("Browser headless mode? (true/false) [false]: ").strip() or "false"
    
    # Server settings
    port = input("Server port? [8001]: ").strip() or "8001"
    
    # Firewall settings
    external_firewall = input("Use external firewall? (true/false) [false]: ").strip() or "false"
    
    # Create .env content
    env_content = f"""# Secure Agentic Browser Environment Configuration
# Generated by setup script on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

# =============================================================================
# API KEYS (REQUIRED)
# =============================================================================
GOOGLE_API_KEY={api_key}

# =============================================================================
# FIREWALL CONFIGURATION
# =============================================================================
USE_EXTERNAL_FIREWALL={external_firewall}
FIREWALL_API_URL=http://localhost:3001/api/validate
FIREWALL_API_KEY=your_external_firewall_api_key_here

# =============================================================================
# BROWSER CONFIGURATION
# =============================================================================
BROWSER_HEADLESS={headless}
BROWSER_TIMEOUT=30000

# =============================================================================
# SERVER CONFIGURATION
# =============================================================================
SERVER_HOST=0.0.0.0
SERVER_PORT={port}
LOG_LEVEL=INFO

# =============================================================================
# AGENT CONFIGURATION
# =============================================================================
MAX_STEPS_PER_TASK=20
AGENT_TIMEOUT=300
DEFAULT_WAIT_TIME=2

# =============================================================================
# SECURITY SETTINGS
# =============================================================================
ENABLE_FIREWALL=true
STRICT_MODE=true
ALLOW_JAVASCRIPT_URLS=false

# =============================================================================
# DEVELOPMENT SETTINGS
# =============================================================================
DEBUG_MODE=false
VERBOSE_LOGGING=false
SAVE_SCREENSHOTS=false
SCREENSHOT_DIR=./screenshots
"""
    
    # Write .env file
    try:
        with open(".env", "w") as f:
            f.write(env_content)
        
        print(f"\n✅ .env file created successfully!")
        print(f"📁 Location: {env_file.absolute()}")
        
        return True
        
    except Exception as e:
        print(f"❌ Failed to create .env file: {str(e)}")
        return False

def install_python_dotenv():
    """Install python-dotenv package."""
    print("\n📦 Installing python-dotenv package...")
    
    try:
        import subprocess
        import sys
        
        result = subprocess.run([
            sys.executable, "-m", "pip", "install", "python-dotenv"
        ], capture_output=True, text=True)
        
        if result.returncode == 0:
            print("✅ python-dotenv installed successfully!")
            return True
        else:
            print(f"❌ Failed to install python-dotenv: {result.stderr}")
            return False
            
    except Exception as e:
        print(f"❌ Error installing python-dotenv: {str(e)}")
        return False

def verify_setup():
    """Verify that the setup works correctly."""
    print("\n🧪 Verifying environment setup...")
    
    try:
        # Try to load .env
        from dotenv import load_dotenv
        load_dotenv()
        
        # Check if API key is loaded
        api_key = os.getenv("GOOGLE_API_KEY")
        if api_key and api_key != "your_actual_gemini_api_key_here":
            print("✅ Environment variables loaded successfully!")
            print(f"🔑 API Key found (ends with: ...{api_key[-8:]})")
            return True
        else:
            print("❌ API key not found or invalid")
            return False
            
    except ImportError:
        print("❌ python-dotenv not available")
        return False
    except Exception as e:
        print(f"❌ Verification failed: {str(e)}")
        return False

def show_usage_instructions():
    """Show instructions on how to use the environment."""
    print(f"\n🎯 USAGE INSTRUCTIONS")
    print("=" * 60)
    print("Your environment is now configured! Here's how to use it:")
    print()
    print("1️⃣ START THE SERVER:")
    print("   python main.py")
    print()
    print("2️⃣ RUN TESTS:")
    print("   python tests/quick_test.py")
    print("   python run_tests.py")
    print()
    print("3️⃣ INTERACTIVE DEMO:")
    print("   python tests/interactive_demo.py")
    print()
    print("4️⃣ SETUP SCRIPT:")
    print("   ./setup_and_test.sh")
    print()
    print("💡 TIPS:")
    print("   • Your API key is now loaded automatically")
    print("   • Edit .env file to change configuration")
    print("   • Never commit .env to version control")
    print("   • The .gitignore file protects your secrets")

def main():
    """Run the complete environment setup."""
    print("🚀 Starting Environment Setup...")
    
    # Step 1: Install python-dotenv
    dotenv_installed = True
    try:
        import dotenv
    except ImportError:
        dotenv_installed = install_python_dotenv()
    
    if not dotenv_installed:
        print("\n⚠️  python-dotenv installation failed")
        print("💡 You can still set environment variables manually:")
        print("   export GOOGLE_API_KEY='your_api_key'")
        return False
    
    # Step 2: Create .env file
    env_created = create_env_file()
    
    if not env_created:
        return False
    
    # Step 3: Verify setup
    setup_verified = verify_setup()
    
    if setup_verified:
        show_usage_instructions()
        print("\n🎉 Environment setup completed successfully!")
        return True
    else:
        print("\n🔧 Setup completed but verification failed")
        print("💡 Try running manually: export GOOGLE_API_KEY='your_key'")
        return False

if __name__ == "__main__":
    try:
        from datetime import datetime
        success = main()
        exit(0 if success else 1)
    except KeyboardInterrupt:
        print("\n\n⏹️ Setup cancelled by user")
        exit(1)
    except Exception as e:
        print(f"\n💥 Unexpected error: {str(e)}")
        exit(1)